version: 2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    

jobs:
  build:
    filters:
      branches:
        only:
          - main

    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd ./functions;  npm install
      - run: npm install --save-dev firebase-tools
      - run:
          name: Build end
          command: echo 'end'
      - run: npm install --save-dev firebase-tools
      - run:
          name: Firebase Deploy
          command: cd ./functions; npm run deploy --token "$FIREBASE_TOKEN"

